# Generated by Django 4.2.30 on 2026-08-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='student',
        ),
    ]
